const fastCsv = require("fast-csv");
const fs = require('fs');

const express = require('express')
const cors = require('cors')
const path = require('path')

// Configure express server
const app = express()
const port = 3000

function read_data() {
    // Read data from 'csv' file
    return [
      {
          "seq": "1",
          "name/first": "Katharine",
          "name/last": "Alvarez",
          "age": "64",
          "street": "Naleg View",
          "city": "Dogcuaso",
          "state": "TN",
          "zip": "28241",
          "dollar": "2507.03",
          "pick": "YELLOW",
          "date": "11/24/1972"
      },
      {
          "seq": "2",
          "name/first": "Marian",
          "name/last": "Nguyen",
          "age": "48",
          "street": "Cafvob Loop",
          "city": "Fonlatnet",
          "state": "OK",
          "zip": "34861",
          "dollar": "720.09",
          "pick": "WHITE",
          "date": "02/01/2037"
      },
      {
          "seq": "3",
          "name/first": "Milton",
          "name/last": "Oliver",
          "age": "25",
          "street": "Kunza Manor",
          "city": "Buitazar",
          "state": "FL",
          "zip": "41589",
          "dollar": "3652.63",
          "pick": "WHITE",
          "date": "09/03/1949"
      },
      {
          "seq": "4",
          "name/first": "Teresa",
          "name/last": "Day",
          "age": "22",
          "street": "Woahu View",
          "city": "Jobeswug",
          "state": "OR",
          "zip": "48867",
          "dollar": "4411.66",
          "pick": "RED",
          "date": "06/21/1990"
      },
      {
          "seq": "5",
          "name/first": "Sadie",
          "name/last": "Greer",
          "age": "57",
          "street": "Wulsab River",
          "city": "Refgamsu",
          "state": "ND",
          "zip": "92622",
          "dollar": "5340.70",
          "pick": "WHITE",
          "date": "05/03/1907"
      },
      {
          "seq": "6",
          "name/first": "Clyde",
          "name/last": "Blake",
          "age": "57",
          "street": "Movah Loop",
          "city": "Uwouhse",
          "state": "OR",
          "zip": "51371",
          "dollar": "2829.94",
          "pick": "RED",
          "date": "09/22/2018"
      },
      {
          "seq": "7",
          "name/first": "Lizzie",
          "name/last": "Hanson",
          "age": "54",
          "street": "Titrat Way",
          "city": "Heurjog",
          "state": "MT",
          "zip": "53014",
          "dollar": "9019.01",
          "pick": "RED",
          "date": "05/10/2062"
      },
      {
          "seq": "8",
          "name/first": "Lida",
          "name/last": "Thompson",
          "age": "40",
          "street": "Wopa Parkway",
          "city": "Iwuuliumo",
          "state": "KY",
          "zip": "46464",
          "dollar": "2282.05",
          "pick": "YELLOW",
          "date": "02/16/2056"
      },
      {
          "seq": "9",
          "name/first": "Timothy",
          "name/last": "Hamilton",
          "age": "35",
          "street": "Nupbe Trail",
          "city": "Nikumfir",
          "state": "VA",
          "zip": "33123",
          "dollar": "9437.48",
          "pick": "GREEN",
          "date": "02/25/1982"
      },
      {
          "seq": "10",
          "name/first": "Irene",
          "name/last": "Beck",
          "age": "25",
          "street": "Cata Grove",
          "city": "Vulashe",
          "state": "MI",
          "zip": "46609",
          "dollar": "6295.36",
          "pick": "WHITE",
          "date": "01/02/2064"
      },
      {
          "seq": "11",
          "name/first": "Harvey",
          "name/last": "Nash",
          "age": "39",
          "street": "Zabdi Circle",
          "city": "Piftusbup",
          "state": "HI",
          "zip": "74173",
          "dollar": "3971.82",
          "pick": "WHITE",
          "date": "01/29/2064"
      },
      {
          "seq": "12",
          "name/first": "Alma",
          "name/last": "Cross",
          "age": "36",
          "street": "Niuco Pass",
          "city": "Tosgecu",
          "state": "ID",
          "zip": "59315",
          "dollar": "8153.67",
          "pick": "RED",
          "date": "04/21/1977"
      },
      {
          "seq": "13",
          "name/first": "Earl",
          "name/last": "Mills",
          "age": "42",
          "street": "Unkik Path",
          "city": "Bettufzar",
          "state": "IN",
          "zip": "02064",
          "dollar": "4462.40",
          "pick": "YELLOW",
          "date": "11/29/1928"
      },
      {
          "seq": "14",
          "name/first": "Edith",
          "name/last": "Black",
          "age": "51",
          "street": "Maho Grove",
          "city": "Ajehudga",
          "state": "GA",
          "zip": "87090",
          "dollar": "8194.41",
          "pick": "YELLOW",
          "date": "05/08/1912"
      },
      {
          "seq": "15",
          "name/first": "Louis",
          "name/last": "Flores",
          "age": "57",
          "street": "Zetwas Path",
          "city": "Upidutmi",
          "state": "PA",
          "zip": "20849",
          "dollar": "4935.37",
          "pick": "YELLOW",
          "date": "12/10/1914"
      },
      {
          "seq": "16",
          "name/first": "Lulu",
          "name/last": "Luna",
          "age": "23",
          "street": "Kawi Extension",
          "city": "Kahnukji",
          "state": "MO",
          "zip": "56586",
          "dollar": "7590.88",
          "pick": "GREEN",
          "date": "08/12/1961"
      },
      {
          "seq": "17",
          "name/first": "Maude",
          "name/last": "McLaughlin",
          "age": "47",
          "street": "Fizge Way",
          "city": "Cutriziv",
          "state": "KS",
          "zip": "02902",
          "dollar": "3821.01",
          "pick": "WHITE",
          "date": "08/03/1927"
      },
      {
          "seq": "18",
          "name/first": "Sallie",
          "name/last": "Hill",
          "age": "50",
          "street": "Zavu Loop",
          "city": "Gimepaw",
          "state": "AL",
          "zip": "12150",
          "dollar": "3004.05",
          "pick": "BLUE",
          "date": "05/04/1985"
      },
      {
          "seq": "19",
          "name/first": "Mable",
          "name/last": "Webster",
          "age": "41",
          "street": "Meldol Path",
          "city": "Anugokwuh",
          "state": "AZ",
          "zip": "92131",
          "dollar": "5277.61",
          "pick": "RED",
          "date": "06/24/2041"
      },
      {
          "seq": "20",
          "name/first": "Eula",
          "name/last": "Blair",
          "age": "34",
          "street": "Pevew River",
          "city": "Vutahep",
          "state": "UT",
          "zip": "56045",
          "dollar": "5613.38",
          "pick": "RED",
          "date": "09/20/1925"
      },
      {
          "seq": "21",
          "name/first": "Loretta",
          "name/last": "Chavez",
          "age": "32",
          "street": "Wudcuk Manor",
          "city": "Nermesma",
          "state": "OH",
          "zip": "42162",
          "dollar": "5048.79",
          "pick": "WHITE",
          "date": "09/13/1915"
      },
      {
          "seq": "22",
          "name/first": "Lizzie",
          "name/last": "Scott",
          "age": "26",
          "street": "Lorbu Key",
          "city": "Dihodpod",
          "state": "KY",
          "zip": "51695",
          "dollar": "5605.51",
          "pick": "YELLOW",
          "date": "10/25/2006"
      },
      {
          "seq": "23",
          "name/first": "Thomas",
          "name/last": "Wilkins",
          "age": "22",
          "street": "Wujdo Glen",
          "city": "Girimi",
          "state": "NV",
          "zip": "90200",
          "dollar": "6082.00",
          "pick": "BLUE",
          "date": "09/28/2004"
      },
      {
          "seq": "24",
          "name/first": "Louise",
          "name/last": "Holmes",
          "age": "44",
          "street": "Voba Drive",
          "city": "Dolmaznaf",
          "state": "MI",
          "zip": "53858",
          "dollar": "1036.72",
          "pick": "BLUE",
          "date": "01/14/1925"
      },
      {
          "seq": "25",
          "name/first": "Donald",
          "name/last": "Murray",
          "age": "47",
          "street": "Afelah Mill",
          "city": "Vitezut",
          "state": "SC",
          "zip": "13894",
          "dollar": "5092.61",
          "pick": "WHITE",
          "date": "04/16/1989"
      },
      {
          "seq": "26",
          "name/first": "Carolyn",
          "name/last": "Lewis",
          "age": "54",
          "street": "Riaca Pike",
          "city": "Fomkoola",
          "state": "AR",
          "zip": "97051",
          "dollar": "6943.71",
          "pick": "GREEN",
          "date": "12/30/2034"
      },
      {
          "seq": "27",
          "name/first": "Bill",
          "name/last": "Henry",
          "age": "56",
          "street": "Afhu Highway",
          "city": "Wigeve",
          "state": "NE",
          "zip": "00538",
          "dollar": "3132.29",
          "pick": "YELLOW",
          "date": "11/08/1909"
      },
      {
          "seq": "28",
          "name/first": "Katie",
          "name/last": "King",
          "age": "54",
          "street": "Tahcej Court",
          "city": "Nojuge",
          "state": "OH",
          "zip": "89310",
          "dollar": "5650.02",
          "pick": "YELLOW",
          "date": "10/04/1968"
      },
      {
          "seq": "29",
          "name/first": "Douglas",
          "name/last": "Maxwell",
          "age": "55",
          "street": "Cafsi Park",
          "city": "Nuwzelat",
          "state": "IA",
          "zip": "08360",
          "dollar": "5993.59",
          "pick": "GREEN",
          "date": "04/21/1926"
      },
      {
          "seq": "30",
          "name/first": "Justin",
          "name/last": "Santos",
          "age": "35",
          "street": "Nuca Road",
          "city": "Pofgosik",
          "state": "KY",
          "zip": "52450",
          "dollar": "4004.49",
          "pick": "WHITE",
          "date": "01/15/2044"
      },
      {
          "seq": "31",
          "name/first": "Earl",
          "name/last": "Jensen",
          "age": "23",
          "street": "Wotha Lane",
          "city": "Henpelni",
          "state": "SD",
          "zip": "71422",
          "dollar": "7208.26",
          "pick": "YELLOW",
          "date": "01/22/2068"
      },
      {
          "seq": "32",
          "name/first": "Micheal",
          "name/last": "Carpenter",
          "age": "35",
          "street": "Muhag Drive",
          "city": "Guckejwe",
          "state": "OR",
          "zip": "07130",
          "dollar": "6360.05",
          "pick": "BLUE",
          "date": "09/19/1913"
      },
      {
          "seq": "33",
          "name/first": "Fanny",
          "name/last": "Tran",
          "age": "62",
          "street": "Calbi Drive",
          "city": "Dufkimni",
          "state": "WY",
          "zip": "35703",
          "dollar": "4668.42",
          "pick": "RED",
          "date": "11/11/2001"
      },
      {
          "seq": "34",
          "name/first": "Delia",
          "name/last": "Parks",
          "age": "63",
          "street": "Upore Ridge",
          "city": "Pucucibe",
          "state": "WV",
          "zip": "64900",
          "dollar": "5466.06",
          "pick": "GREEN",
          "date": "12/04/1937"
      },
      {
          "seq": "35",
          "name/first": "Margaret",
          "name/last": "Ward",
          "age": "54",
          "street": "Tiriw Avenue",
          "city": "Jojrase",
          "state": "SD",
          "zip": "87726",
          "dollar": "1484.01",
          "pick": "BLUE",
          "date": "10/12/2008"
      },
      {
          "seq": "36",
          "name/first": "James",
          "name/last": "Miller",
          "age": "22",
          "street": "Cimhu Path",
          "city": "Dodvuru",
          "state": "AZ",
          "zip": "06698",
          "dollar": "6787.37",
          "pick": "GREEN",
          "date": "05/08/2033"
      },
      {
          "seq": "37",
          "name/first": "Landon",
          "name/last": "Hoffman",
          "age": "51",
          "street": "Idoget Avenue",
          "city": "Fuhnujha",
          "state": "MN",
          "zip": "49339",
          "dollar": "9114.64",
          "pick": "BLUE",
          "date": "12/27/1976"
      },
      {
          "seq": "38",
          "name/first": "Millie",
          "name/last": "Meyer",
          "age": "37",
          "street": "Faru Square",
          "city": "Arilozoz",
          "state": "NH",
          "zip": "84074",
          "dollar": "4607.90",
          "pick": "WHITE",
          "date": "06/05/2056"
      },
      {
          "seq": "39",
          "name/first": "Scott",
          "name/last": "Gonzales",
          "age": "42",
          "street": "Papoh Avenue",
          "city": "Nusonrov",
          "state": "RI",
          "zip": "74528",
          "dollar": "7028.36",
          "pick": "GREEN",
          "date": "06/29/2044"
      },
      {
          "seq": "40",
          "name/first": "Addie",
          "name/last": "Osborne",
          "age": "65",
          "street": "Opecu Street",
          "city": "Azowewi",
          "state": "FL",
          "zip": "76523",
          "dollar": "6149.86",
          "pick": "GREEN",
          "date": "04/11/1965"
      },
      {
          "seq": "41",
          "name/first": "Dale",
          "name/last": "Klein",
          "age": "33",
          "street": "Fonboh Street",
          "city": "Vutmowi",
          "state": "AZ",
          "zip": "89868",
          "dollar": "5335.20",
          "pick": "GREEN",
          "date": "09/29/2035"
      },
      {
          "seq": "42",
          "name/first": "Cynthia",
          "name/last": "Hodges",
          "age": "39",
          "street": "Banbas Parkway",
          "city": "Coisese",
          "state": "AK",
          "zip": "37604",
          "dollar": "5221.45",
          "pick": "WHITE",
          "date": "08/25/1979"
      },
      {
          "seq": "43",
          "name/first": "Patrick",
          "name/last": "Weaver",
          "age": "23",
          "street": "Nido Road",
          "city": "Zafaduzem",
          "state": "VT",
          "zip": "60323",
          "dollar": "874.93",
          "pick": "BLUE",
          "date": "01/11/2059"
      },
      {
          "seq": "44",
          "name/first": "Emma",
          "name/last": "Swanson",
          "age": "57",
          "street": "Leno Heights",
          "city": "Wevmorota",
          "state": "DE",
          "zip": "13097",
          "dollar": "613.13",
          "pick": "YELLOW",
          "date": "10/18/2009"
      },
      {
          "seq": "45",
          "name/first": "Theresa",
          "name/last": "Stevens",
          "age": "41",
          "street": "Duga Park",
          "city": "Tadefumu",
          "state": "AR",
          "zip": "92746",
          "dollar": "249.39",
          "pick": "RED",
          "date": "02/04/1939"
      },
      {
          "seq": "46",
          "name/first": "Angel",
          "name/last": "Sparks",
          "age": "61",
          "street": "Surez Ridge",
          "city": "Jusetup",
          "state": "PA",
          "zip": "98281",
          "dollar": "654.52",
          "pick": "YELLOW",
          "date": "12/13/1944"
      },
      {
          "seq": "47",
          "name/first": "Carl",
          "name/last": "Fuller",
          "age": "37",
          "street": "Tawad Street",
          "city": "Kifokeci",
          "state": "KY",
          "zip": "19654",
          "dollar": "3948.54",
          "pick": "BLUE",
          "date": "04/17/1902"
      },
      {
          "seq": "48",
          "name/first": "Eugene",
          "name/last": "Brown",
          "age": "33",
          "street": "Wifib Terrace",
          "city": "Mazebasu",
          "state": "LA",
          "zip": "78414",
          "dollar": "1883.05",
          "pick": "BLUE",
          "date": "11/11/2051"
      },
      {
          "seq": "49",
          "name/first": "Virgie",
          "name/last": "Jefferson",
          "age": "53",
          "street": "Azsi Street",
          "city": "Wiekizoh",
          "state": "VA",
          "zip": "07364",
          "dollar": "7883.95",
          "pick": "BLUE",
          "date": "07/15/2026"
      },
      {
          "seq": "50",
          "name/first": "Jean",
          "name/last": "Rivera",
          "age": "32",
          "street": "Tacco Place",
          "city": "Nanlauza",
          "state": "CO",
          "zip": "29852",
          "dollar": "9669.84",
          "pick": "BLUE",
          "date": "12/02/1933"
      },
      {
          "seq": "51",
          "name/first": "Carolyn",
          "name/last": "Gordon",
          "age": "41",
          "street": "Dipsib Turnpike",
          "city": "Mimejgaj",
          "state": "MT",
          "zip": "63274",
          "dollar": "6033.48",
          "pick": "YELLOW",
          "date": "04/29/2056"
      },
      {
          "seq": "52",
          "name/first": "Addie",
          "name/last": "Bishop",
          "age": "64",
          "street": "Bemav Drive",
          "city": "Dehmikpic",
          "state": "NY",
          "zip": "30687",
          "dollar": "7175.34",
          "pick": "YELLOW",
          "date": "03/02/1987"
      },
      {
          "seq": "53",
          "name/first": "Gertrude",
          "name/last": "Anderson",
          "age": "56",
          "street": "Cugmoh Way",
          "city": "Kobejfe",
          "state": "MA",
          "zip": "85001",
          "dollar": "6289.65",
          "pick": "BLUE",
          "date": "09/20/2067"
      },
      {
          "seq": "54",
          "name/first": "Viola",
          "name/last": "Tyler",
          "age": "49",
          "street": "Noefo Point",
          "city": "Wissobme",
          "state": "NE",
          "zip": "47470",
          "dollar": "4341.32",
          "pick": "GREEN",
          "date": "11/17/1940"
      },
      {
          "seq": "55",
          "name/first": "Lida",
          "name/last": "Riley",
          "age": "23",
          "street": "Unal Grove",
          "city": "Zucojis",
          "state": "MS",
          "zip": "91046",
          "dollar": "9188.50",
          "pick": "YELLOW",
          "date": "08/10/2019"
      },
      {
          "seq": "56",
          "name/first": "Gavin",
          "name/last": "Powers",
          "age": "27",
          "street": "Ulsu Circle",
          "city": "Orhomeg",
          "state": "GA",
          "zip": "92076",
          "dollar": "5674.47",
          "pick": "RED",
          "date": "05/26/1947"
      },
      {
          "seq": "57",
          "name/first": "Louise",
          "name/last": "Norman",
          "age": "37",
          "street": "Erien Center",
          "city": "Gagoruk",
          "state": "MI",
          "zip": "64646",
          "dollar": "6046.11",
          "pick": "RED",
          "date": "11/13/1904"
      },
      {
          "seq": "58",
          "name/first": "Barry",
          "name/last": "West",
          "age": "34",
          "street": "Ofun Way",
          "city": "Ketahoh",
          "state": "WV",
          "zip": "26194",
          "dollar": "2296.93",
          "pick": "BLUE",
          "date": "06/24/1945"
      },
      {
          "seq": "59",
          "name/first": "Tony",
          "name/last": "Roberts",
          "age": "46",
          "street": "Lujsof Way",
          "city": "Giulgi",
          "state": "MA",
          "zip": "49992",
          "dollar": "2744.25",
          "pick": "RED",
          "date": "08/31/2046"
      },
      {
          "seq": "60",
          "name/first": "Ronnie",
          "name/last": "Wheeler",
          "age": "36",
          "street": "Haem Road",
          "city": "Kavfihdup",
          "state": "AK",
          "zip": "29073",
          "dollar": "1838.38",
          "pick": "WHITE",
          "date": "03/14/1906"
      },
      {
          "seq": "61",
          "name/first": "Lora",
          "name/last": "Snyder",
          "age": "58",
          "street": "Oveolu Turnpike",
          "city": "Dipuzhuj",
          "state": "TN",
          "zip": "40226",
          "dollar": "5727.56",
          "pick": "RED",
          "date": "12/14/1907"
      },
      {
          "seq": "62",
          "name/first": "Ethan",
          "name/last": "Wolfe",
          "age": "43",
          "street": "Vigoko Square",
          "city": "Kedope",
          "state": "MA",
          "zip": "32541",
          "dollar": "4664.39",
          "pick": "BLUE",
          "date": "05/31/1901"
      },
      {
          "seq": "63",
          "name/first": "Rosie",
          "name/last": "Allen",
          "age": "57",
          "street": "Netwo Park",
          "city": "Jecopi",
          "state": "AL",
          "zip": "54187",
          "dollar": "7921.05",
          "pick": "YELLOW",
          "date": "03/04/1984"
      },
      {
          "seq": "64",
          "name/first": "Charlie",
          "name/last": "Jenkins",
          "age": "39",
          "street": "Ceres Glen",
          "city": "Ikatalcav",
          "state": "TN",
          "zip": "15231",
          "dollar": "6419.81",
          "pick": "WHITE",
          "date": "06/21/1980"
      },
      {
          "seq": "65",
          "name/first": "Willie",
          "name/last": "Myers",
          "age": "64",
          "street": "Nopdu Terrace",
          "city": "Fossuwjil",
          "state": "AR",
          "zip": "98987",
          "dollar": "2990.34",
          "pick": "YELLOW",
          "date": "03/29/2036"
      },
      {
          "seq": "66",
          "name/first": "Cody",
          "name/last": "Barker",
          "age": "39",
          "street": "Dasva Heights",
          "city": "Utupalte",
          "state": "OH",
          "zip": "68460",
          "dollar": "7462.16",
          "pick": "WHITE",
          "date": "08/21/1954"
      },
      {
          "seq": "67",
          "name/first": "Ina",
          "name/last": "Evans",
          "age": "34",
          "street": "Midwic Square",
          "city": "Sanave",
          "state": "AL",
          "zip": "09224",
          "dollar": "4625.87",
          "pick": "YELLOW",
          "date": "04/04/1998"
      },
      {
          "seq": "68",
          "name/first": "Ophelia",
          "name/last": "Cobb",
          "age": "55",
          "street": "Ovira Turnpike",
          "city": "Avugihnan",
          "state": "WI",
          "zip": "95382",
          "dollar": "9377.45",
          "pick": "GREEN",
          "date": "03/09/2048"
      },
      {
          "seq": "69",
          "name/first": "Kate",
          "name/last": "Hudson",
          "age": "47",
          "street": "Cojivi Loop",
          "city": "Vagigda",
          "state": "NM",
          "zip": "40698",
          "dollar": "4341.40",
          "pick": "BLUE",
          "date": "05/20/1915"
      },
      {
          "seq": "70",
          "name/first": "Gene",
          "name/last": "Craig",
          "age": "23",
          "street": "Late Circle",
          "city": "Anforpa",
          "state": "LA",
          "zip": "34946",
          "dollar": "4271.39",
          "pick": "WHITE",
          "date": "11/17/1935"
      },
      {
          "seq": "71",
          "name/first": "Herbert",
          "name/last": "Page",
          "age": "51",
          "street": "Luni Parkway",
          "city": "Nuzvunson",
          "state": "MT",
          "zip": "09982",
          "dollar": "9339.55",
          "pick": "YELLOW",
          "date": "06/06/1998"
      },
      {
          "seq": "72",
          "name/first": "Jordan",
          "name/last": "Bates",
          "age": "37",
          "street": "Wutahe Court",
          "city": "Cawmiceze",
          "state": "HI",
          "zip": "19841",
          "dollar": "7605.83",
          "pick": "RED",
          "date": "05/19/2028"
      },
      {
          "seq": "73",
          "name/first": "Addie",
          "name/last": "Lindsey",
          "age": "23",
          "street": "Selwiv Way",
          "city": "Epufamep",
          "state": "KS",
          "zip": "08656",
          "dollar": "3343.69",
          "pick": "YELLOW",
          "date": "09/07/1969"
      },
      {
          "seq": "74",
          "name/first": "Dora",
          "name/last": "Andrews",
          "age": "36",
          "street": "Muun Glen",
          "city": "Ofirenfil",
          "state": "SC",
          "zip": "32470",
          "dollar": "8062.97",
          "pick": "GREEN",
          "date": "12/09/2012"
      },
      {
          "seq": "75",
          "name/first": "Louise",
          "name/last": "Townsend",
          "age": "52",
          "street": "Fofsor Point",
          "city": "Naredkis",
          "state": "UT",
          "zip": "32699",
          "dollar": "9935.70",
          "pick": "YELLOW",
          "date": "02/26/1910"
      },
      {
          "seq": "76",
          "name/first": "Bobby",
          "name/last": "Wise",
          "age": "53",
          "street": "Woluce Ridge",
          "city": "Rotifri",
          "state": "NV",
          "zip": "33296",
          "dollar": "2893.24",
          "pick": "BLUE",
          "date": "08/05/2051"
      },
      {
          "seq": "77",
          "name/first": "Vera",
          "name/last": "Holmes",
          "age": "45",
          "street": "Ebjob Pass",
          "city": "Zoedhe",
          "state": "AK",
          "zip": "96094",
          "dollar": "6387.38",
          "pick": "GREEN",
          "date": "11/01/2014"
      },
      {
          "seq": "78",
          "name/first": "Ida",
          "name/last": "Sullivan",
          "age": "42",
          "street": "Sedbi Manor",
          "city": "Zuavaze",
          "state": "VT",
          "zip": "51141",
          "dollar": "192.50",
          "pick": "WHITE",
          "date": "03/24/1911"
      },
      {
          "seq": "79",
          "name/first": "Phillip",
          "name/last": "Patton",
          "age": "46",
          "street": "Fomel View",
          "city": "Adneul",
          "state": "MD",
          "zip": "14331",
          "dollar": "2102.42",
          "pick": "BLUE",
          "date": "12/17/2038"
      },
      {
          "seq": "80",
          "name/first": "Ryan",
          "name/last": "Tran",
          "age": "55",
          "street": "Gohe Terrace",
          "city": "Kesumba",
          "state": "TX",
          "zip": "82346",
          "dollar": "2913.06",
          "pick": "RED",
          "date": "12/04/1997"
      },
      {
          "seq": "81",
          "name/first": "Seth",
          "name/last": "Hampton",
          "age": "61",
          "street": "Rufgus Pass",
          "city": "Neblasi",
          "state": "TN",
          "zip": "71352",
          "dollar": "4186.35",
          "pick": "GREEN",
          "date": "02/13/1971"
      },
      {
          "seq": "82",
          "name/first": "Tony",
          "name/last": "Adams",
          "age": "44",
          "street": "Lede Grove",
          "city": "Ocovidu",
          "state": "IA",
          "zip": "79335",
          "dollar": "1350.85",
          "pick": "YELLOW",
          "date": "12/14/1927"
      },
      {
          "seq": "83",
          "name/first": "Virgie",
          "name/last": "Washington",
          "age": "30",
          "street": "Vumkib Turnpike",
          "city": "Diwucsal",
          "state": "NV",
          "zip": "04482",
          "dollar": "7444.33",
          "pick": "GREEN",
          "date": "04/29/1979"
      },
      {
          "seq": "84",
          "name/first": "George",
          "name/last": "Leonard",
          "age": "65",
          "street": "Kewek Path",
          "city": "Fifviswi",
          "state": "AZ",
          "zip": "39806",
          "dollar": "2357.75",
          "pick": "WHITE",
          "date": "06/17/1900"
      },
      {
          "seq": "85",
          "name/first": "Dean",
          "name/last": "Moody",
          "age": "38",
          "street": "Domvet Highway",
          "city": "Ofuvus",
          "state": "NV",
          "zip": "13513",
          "dollar": "5850.78",
          "pick": "RED",
          "date": "08/03/2016"
      },
      {
          "seq": "86",
          "name/first": "Marion",
          "name/last": "Hill",
          "age": "44",
          "street": "Noewu View",
          "city": "Iwuneza",
          "state": "WA",
          "zip": "75956",
          "dollar": "8178.09",
          "pick": "GREEN",
          "date": "11/02/1993"
      },
      {
          "seq": "87",
          "name/first": "Shawn",
          "name/last": "Elliott",
          "age": "23",
          "street": "Sulir Court",
          "city": "Maonibe",
          "state": "TX",
          "zip": "26317",
          "dollar": "4557.26",
          "pick": "BLUE",
          "date": "03/12/2016"
      },
      {
          "seq": "88",
          "name/first": "Pauline",
          "name/last": "Hopkins",
          "age": "53",
          "street": "Eguuce Mill",
          "city": "Vumizi",
          "state": "ME",
          "zip": "78147",
          "dollar": "2840.77",
          "pick": "GREEN",
          "date": "03/14/1923"
      },
      {
          "seq": "89",
          "name/first": "Addie",
          "name/last": "Owen",
          "age": "55",
          "street": "Kose Drive",
          "city": "Buwugowed",
          "state": "IN",
          "zip": "11537",
          "dollar": "8608.18",
          "pick": "YELLOW",
          "date": "11/04/1939"
      },
      {
          "seq": "90",
          "name/first": "Brian",
          "name/last": "Chambers",
          "age": "52",
          "street": "Bebuj Terrace",
          "city": "Viemarop",
          "state": "VA",
          "zip": "59449",
          "dollar": "6900.39",
          "pick": "WHITE",
          "date": "04/02/1918"
      },
      {
          "seq": "91",
          "name/first": "Maurice",
          "name/last": "Clayton",
          "age": "21",
          "street": "Ohotep Boulevard",
          "city": "Warewkez",
          "state": "AK",
          "zip": "19132",
          "dollar": "7601.05",
          "pick": "RED",
          "date": "02/26/1956"
      },
      {
          "seq": "92",
          "name/first": "Landon",
          "name/last": "Davis",
          "age": "44",
          "street": "Hirpe Pass",
          "city": "Suzbeti",
          "state": "MT",
          "zip": "57016",
          "dollar": "9960.14",
          "pick": "BLUE",
          "date": "04/14/2056"
      },
      {
          "seq": "93",
          "name/first": "Elva",
          "name/last": "Sanders",
          "age": "39",
          "street": "Kaba Street",
          "city": "Kagbife",
          "state": "AR",
          "zip": "56751",
          "dollar": "3745.12",
          "pick": "YELLOW",
          "date": "05/15/1970"
      },
      {
          "seq": "94",
          "name/first": "Brett",
          "name/last": "Carr",
          "age": "57",
          "street": "Monzir Boulevard",
          "city": "Matkupa",
          "state": "IN",
          "zip": "09817",
          "dollar": "999.05",
          "pick": "YELLOW",
          "date": "01/01/1953"
      },
      {
          "seq": "95",
          "name/first": "Andrew",
          "name/last": "Grant",
          "age": "30",
          "street": "Ohba Heights",
          "city": "Volalfiw",
          "state": "CA",
          "zip": "15592",
          "dollar": "8825.44",
          "pick": "GREEN",
          "date": "08/09/2049"
      },
      {
          "seq": "96",
          "name/first": "Bruce",
          "name/last": "Guerrero",
          "age": "35",
          "street": "Tiuw Avenue",
          "city": "Raveev",
          "state": "LA",
          "zip": "51975",
          "dollar": "5253.40",
          "pick": "YELLOW",
          "date": "08/15/1993"
      },
      {
          "seq": "97",
          "name/first": "Dylan",
          "name/last": "Graham",
          "age": "36",
          "street": "Otubo Pass",
          "city": "Obpeisi",
          "state": "LA",
          "zip": "65950",
          "dollar": "7259.53",
          "pick": "YELLOW",
          "date": "11/29/1947"
      },
      {
          "seq": "98",
          "name/first": "Clifford",
          "name/last": "McCormick",
          "age": "63",
          "street": "Lopto Road",
          "city": "Zejozic",
          "state": "CO",
          "zip": "53671",
          "dollar": "341.88",
          "pick": "YELLOW",
          "date": "07/04/1992"
      },
      {
          "seq": "99",
          "name/first": "Rosalie",
          "name/last": "Baker",
          "age": "38",
          "street": "Rodaka Drive",
          "city": "Sudevku",
          "state": "ME",
          "zip": "41367",
          "dollar": "5575.81",
          "pick": "BLUE",
          "date": "03/13/1917"
      },
      {
          "seq": "100",
          "name/first": "Georgia",
          "name/last": "Figueroa",
          "age": "29",
          "street": "Etzil Street",
          "city": "Jirmoser",
          "state": "MI",
          "zip": "20531",
          "dollar": "6988.43",
          "pick": "GREEN",
          "date": "06/09/2060"
      }
  ]
}

app.use(cors())
app.use('/static', express.static(path.join(__dirname, 'static')));

// root endpoint
app.get('/', (req, res) => {
  res.json({"message": "Hello World"})
})

// data endpoint
app.get('/data', (req, res) => {
    let data = read_data(res)
    res.json(data)
  })

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
